ignore_merge_commits = false
tag_prefix = "v"
branch_whitelist = []
pre_bump_hooks = [
    "cargo build --release",
    "cargo set-version {{version}}",
    "cargo check --release",
    "git add :/Cargo.lock",
]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = [
    { signature = "Marcin Puc", username = "tranzystorek-io" },
    { signature = "Bartosz Dec", username = "Qsionc" },
]

[bump_profiles]
